name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: npm install
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: testing
    if: github.event_name == 'push' && github.ref == 'refs/head/master'

    steps:
      - uses: actions/checkout@v2
      - name: SCP to digitalocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSHKEY }}
          source: "*"
          target: "test"
          overwrite: true
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSHKEY }}
          script: |
            cd Flack/
            export NODE_ENV=production
            npm install
            npm run build
            docker-compose build
            docker-compose up -d
