name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: npm ci
      - name: Create env file
        run: |
          touch .env
          echo ACCESS_SECRET_TOKEN=${{ secrets.ACCESS_SECRET_TOKEN }} >> .env
          echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} >> .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
      - name: Test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: testing

    steps:
      - uses: actions/checkout@v2
      - name: SCP to DO
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "*"
          target: "test"
          overwrite: true
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd Flack/
            export NODE_ENV=production
            npm install
            npm run build
            docker-compose build
            docker-compose up -d
